# Generated by Django 4.2.2 on 2023-06-21 18:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Notes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='noteshare',
            name='shared_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='shared_notes', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
